# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
 autoCancel: true

pool: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    for i in {1..3}; do
      echo "Still running... $i"
      sleep 10
    done
  displayName: 'Simulate long-running task (5 minutes)'
